Feature/two tables db
sraduhin/python_invest_dashboard pull request #6
Opened 2022-06-19 16:31 UTC by sraduhin

2022-06-19 17:02 UTC, sobrabd requested changes
удалить дб из гита
убрать ключи из гита

2022-06-20 09:16 UTC, sraduhin commented on webapp/get_portfolios.py
> +                save_portfolios(account_id, type, data, expected_yield, total_currencies, total_shares, total_etf, total_bonds, total_futures)
а как же solid?

2022-06-20 09:18 UTC, sraduhin commented on webapp/get_portfolios.py
> +                data = True
это не нужно. Снес

2022-06-20 12:27 UTC, sraduhin commented on webapp/model.py
> +    figi = db.Column(db.String, nullable=False)
пока уберу

2022-06-20 13:33 UTC, sraduhin commented on webapp/model.py
> +    account_id = db.Column(db.Integer, db.ForeignKey(Securities.account_id))
блэт(

2022-06-21 15:08 UTC, sobrabd commented on queries.py
> +with app.app_context():
я бы внес контекст в каждую функцию, сейчас это странно выглядит, ты не можешь воспользоваться этими фнкциями нигде в дргом месте, т.к. они привязаны к этому контексту

2022-06-22 09:35 UTC, merged